### ISSUE TITLE
Ghillie script github gone again?

### ISSUE THREAD

**Issue by Activeo2o** [eemj/teleport#1]
What happened? :c

**Comment by Activeo2o** [comment]
Do you have a discord where you update your stuff and stuffz? :p

**Comment by eemj** [comment]
Pretty much removed everything, I don't feel like wasting time with the "_blocks_" pinkie keeps doing against this script and the required packet. Also I would like to keep my discord private.

**Comment by Activeo2o** [comment]
well are you going to keep updating it privately if .. let's say, someones willing to pay for it? :p
