### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Activeo2o** [eemj/teleport#2]
Sorry for bothering, but does this mean it is the end of ghilliefarming once this is fixed? :( dont leave us poor scrubs hanging dude :(

is there a possibility to pay for you updating the script or access to your discord (where you would share it? :p), if so, please let me know where i can reach you except opening new issue requests on github <.<

**Comment by eemj** [comment]
Email me on _*********************_ and I'll send you my Discord there so we can discuss this.
